data-path = "workdir/node-2"
node-private-key-file = "config/keys/node-2"
discovery-enabled = false
static-nodes-file = "config/static-nodes.json"
rpc-http-host = "127.0.0.1"
rpc-http-port = 8546
p2p-host = "127.0.0.1"
p2p-interface = "127.0.0.1"
p2p-port = 30304
genesis-file = "config/genesis.json"
rpc-http-api = [ "ETH", "NET", "WEB3", "ADMIN",]
